added legal terms

diff --git a/scripts/sh/rc b/scripts/sh/rc
--- a/scripts/sh/rc
+++ b/scripts/sh/rc
@@ -618,68 +618,67 @@ run_sysctl () {
   fi
 }
 
+## set up the console vts
 setup_console () {
-  local failed=0
+  local r=0
 
-  test -r /etc/sysconfig/console && . /etc/sysconfig/console
-  # See if we need to do anything
-  if [ -z "${KEYMAP}"         ] && [ -z "${KEYMAP_CORRECTIONS}" ] &&
-     [ -z "${FONT}"           ] && [ -z "${LEGACY_CHARSET}"     ] &&
-     ! is_true "${UNICODE}"; then
+  test -f /etc/sysconfig/console && . /etc/sysconfig/console
+
+  ## See if we need to do anything
+  if test -z "${KEYMAP:-}" -a -z "${KEYMAP_CORRECTIONS:-}" -a \
+    -z "${FONT:-}" -a -z "${LEGACY_CHARSET:-}" && ! is_true "${UNICODE:-}"
+  then
     return 0
   fi
 
-  # There should be no bogus failures below this line!
-  log_info_msg "Setting up Linux console..."
+  ## There should be no bogus failures below this line!
+  log_info_msg "Setting up Linux console ..."
 
-  # Figure out if a framebuffer console is used
-  [ -d /sys/class/graphics/fb0 ] && use_fb=1 || use_fb=0
+  ## Figure out if a framebuffer console is used
+  test -d /sys/class/graphics/fb0 && use_fb=1 || use_fb=0
 
-  # Figure out the command to set the console into the
-  # desired mode
-  is_true "${UNICODE}" &&
+  ## Figure out the command to set the console into the
+  ## desired mode
+  is_true "${UNICODE:-}" &&
   MODE_COMMAND="echo -en '\033%G' && kbd_mode -u" ||
   MODE_COMMAND="echo -en '\033%@\033(K' && kbd_mode -a"
 
-  # On framebuffer consoles, font has to be set for each vt in
-  # UTF-8 mode. This doesn't hurt in non-UTF-8 mode also.
-
-  ! is_true "${use_fb}" || [ -z "${FONT}" ] ||
+  ## On framebuffer consoles, font has to be set for each vt in
+  ## UTF-8 mode. This doesn't hurt in non-UTF-8 mode also.
+  ! is_true "${use_fb}" || test -z "${FONT:-}" ||
     MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"
 
-  # Apply that command to all consoles mentioned in
-  # /etc/inittab. Important: in the UTF-8 mode this should
-  # happen before setfont, otherwise a kernel bug will
-  # show up and the unicode map of the font will not be
-  # used.
-
+  ## Apply that command to all consoles mentioned in
+  ## /etc/inittab. Important: in the UTF-8 mode this should
+  ## happen before setfont, otherwise a kernel bug will
+  ## show up and the unicode map of the font will not be used.
   for TTY in `grep '^[^#].*respawn:/sbin/agetty' /etc/inittab |
-     grep -o '\btty[[:digit:]]*\b'`
-   do
-     openvt -f -w -c ${TTY#tty} -- \
-       /bin/sh -c "${MODE_COMMAND}" || failed=1
-   done
+    grep -o '\btty[[:digit:]]*\b'`
+  do
+    openvt -f -w -c ${TTY#tty} -- sh -c "${MODE_COMMAND}" || r=1
+  done
 
-  # Set the font (if not already set above) and the keymap
-  [ "${use_fb}" == "1" ] || [ -z "${FONT}" ] || setfont $FONT || failed=1
+  ## Set the font (if not already set above) and the keymap
+  if test 1 -eq "${use_fb:-}" -a -n "${FONT:-}" ; then
+    setfont "$FONT" || r=1
+  fi
 
-  [ -z "${KEYMAP}" ] ||
-    loadkeys ${KEYMAP} >/dev/null 2>&1 ||
-    failed=1
+  if test -n "${KEYMAP:-}" ; then
+    loadkeys "${KEYMAP}" > /dev/null 2>&1 || r=1
+  fi
 
-  [ -z "${KEYMAP_CORRECTIONS}" ] ||
-    loadkeys ${KEYMAP_CORRECTIONS} >/dev/null 2>&1 ||
-    failed=1
+  if test -n "${KEYMAP_CORRECTIONS:-}" ; then
+    loadkeys ${KEYMAP_CORRECTIONS} > /dev/null 2>&1 || r=1
+  fi
 
-  # Convert the keymap from $LEGACY_CHARSET to UTF-8
-  [ -z "$LEGACY_CHARSET" ] ||
-     dumpkeys -c "$LEGACY_CHARSET" | loadkeys -u >/dev/null 2>&1 ||
-     failed=1
+  ## Convert the keymap from $LEGACY_CHARSET to UTF-8
+  if test -n "${LEGACY_CHARSET:-}" ; then
+    dumpkeys -c "$LEGACY_CHARSET" | loadkeys -u > /dev/null 2>&1 || r=1
+  fi
 
-  # If any of the commands above failed, the trap at the
-  # top would set $failed to 1
-  ( return $failed )
-  evret "$?"
-  return $failed
+  ## If any of the commands above failed, the trap at the
+  ## top would set $r to 1 (non zero)
+  evret "$r"
+  return "$r"
 }
 
